server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/intuit_demo
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  user:
    datasource:
      driver-class-name: com.mysql.jdbc.Driver

